name: Publish Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-11
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Publish to Maven Central
      run: gradle publishAllPublicationsToMavenCentralRepository
      env: 
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.GPG_PRIVATE_KEY}}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{secrets.SIGNING_KEYID}}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.MAVEN_GPG_PASSPHRASE}}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.MAVENCENTRALUSERNAME}}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.MAVENCENTRALPASSWORD}}
    - name: Publish to Gradle Plugins
      run: gradle :dikt-gradle-plugin:publish -Pgradle.publish.key=${{secrets.GRADLE_PUBLISH_KEY}} -Pgradle.publish.secret=${{secrets.GRADLE_PUBLISH_SECRET}}
    - name: Build IDEA Plugin
      run: gradle :dikt-idea-plugin:assemble
    - name: Upload IDEA Plugin
      uses: actions/upload-artifact@v2
      with:
        path: dikt-idea-plugin/build/distributions
